require 'simple_form_password_with_hints/password_with_hints_input'
require 'simple_form_password_with_hints/password_with_sync_input'
require 'simple_form_password_with_hints/engine'

module SimpleFormPasswordWithHints
end
